name: Update Temperature Data

permissions:
  contents: write

on:
  schedule:
    - cron: "0 16 * * *" # JST 01:00 = UTC 16:00
  workflow_dispatch: # 手動実行も可能

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Fetch and append temperature data
        run: node scripts/fetch_temp.js
      
      - name: Fetch and append forecast temperature data
        run: node scripts/fetch_temp_forecast.js

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          git add data.csv data_forecast.csv

          if ! git diff --staged --quiet; then
            git commit -m "Update temperature data for $(date +'%Y-%m-%d')"
            git push
          else
            echo "No changes to commit."
          fi
